# Generated by Django 5.0.6 on 2024-05-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='kyc',
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.CharField(choices=[('US Dollar $', '$'), ('Pound Sterling £ ', '£'), ('Euro €', '€')], default='US Dollar $', max_length=24),
        ),
    ]
