# Generated by Django 5.0.6 on 2024-05-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_remove_customer_kyc_customer_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='currency',
            field=models.CharField(choices=[('$', 'US Dollar $'), ('£ ', 'Pound Sterling £'), ('€', 'Euro €')], default='$', max_length=24),
        ),
    ]
