# Generated by Django 5.1.2 on 2024-11-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0012_remove_customer_currency_deposit_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='currency',
            field=models.CharField(default='$', max_length=24),
        ),
    ]
