# Generated by Django 5.1.2 on 2024-11-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0016_rename_date_transaction_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet',
            field=models.CharField(default='Generating .......', max_length=200, null=True),
        ),
    ]
